version: '3.8'

services:
  # שירות Kafka
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://localhost:9093  # עדכון הפורט של OUTSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT_INSIDE: 9092
      KAFKA_LISTENER_MODE: broker
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092, OUTSIDE://0.0.0.0:9093  # עדכון הפורט של OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"   # עבור INSIDE
      - "9093:9093"   # עבור OUTSIDE
    depends_on:
      - zookeeper
    networks:
      - backend

  # שירות Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - backend

  # שירות MongoDB
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - backend

  # שירות Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  # שירות structureToKafka
  structuretokafka:
    build:
      context: C:/Users/rango/jobProject/structureToKafka  # תיקיה structureToKafka בנתיב המוחלט
    volumes:
      - C:/Users/rango/jobProject/structureToKafka:/app  # העברת כל התיקיה
    working_dir: /app
    command: python3 /app/main.py  # הרצת קובץ main.py
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - MONGO_URI=mongodb://root:example@mongo:27017
      - REDIS_HOST=redis
    depends_on:
      - kafka
      - mongo
      - redis
    networks:
      - backend

  # שירות redisPart
  redispart:
    build:
      context: C:/Users/rango/jobProject/redisPart  # תיקיה redisPart בנתיב המוחלט
    volumes:
      - C:/Users/rango/jobProject/redisPart:/app  # העברת כל התיקיה
    working_dir: /app
    command: python3 /app/main.py  # הרצת קובץ main.py
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - MONGO_URI=mongodb://root:example@mongo:27017
      - REDIS_HOST=redis
    depends_on:
      - kafka
      - mongo
      - redis
    networks:
      - backend

  # שירות printToScreen
  printtoscreen:
    build:
      context: C:/Users/rango/jobProject/printToScreen  # תיקיה printToScreen בנתיב המוחלט
    volumes:
      - C:/Users/rango/jobProject/printToScreen:/app  # העברת כל התיקיה
    working_dir: /app
    command: python3 /app/main.py  # הרצת קובץ main.py
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - MONGO_URI=mongodb://root:example@mongo:27017
      - REDIS_HOST=redis
    depends_on:
      - kafka
      - mongo
      - redis
    networks:
      - backend

  # שירות kafkaToMongodb
  kafkatomongodb:
    build:
      context: C:/Users/rango/jobProject/kafkaToMongodb  # תיקיה kafkaToMongodb בנתיב המוחלט
    volumes:
      - C:/Users/rango/jobProject/kafkaToMongodb:/app  # העברת כל התיקיה
    working_dir: /app
    command: python3 /app/consumer.py  # הרצת קובץ main.py
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - MONGO_URI=mongodb://root:example@mongo:27017
      - REDIS_HOST=redis
    depends_on:
      - kafka
      - mongo
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
